---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - run: make venv
      - run: make cli
      - run: make deps
      - run: make compile
